apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: load-balancer
spec:
  addresses:
    - 172.18.0.100-172.18.0.110
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
spec:
  ipAddressPools:
    - load-balancer
